project:
  type: website
  output-dir: docs  # GitHub Pages will serve from here
  pre-render: scripts/get-files.r # get markdown files from collaborative obsidian vault
  resources: 
    - CNAME
website:
  site-url: "https://www.groovyweirdo.com"
  title: "Groovy Weirdo Art"
  description: "Groovy Weirdo art portfolio and shop"
  image: "assets/images/groovy-weirdo-logo-360x180.png"
  favicon: assets/images/groovy-weirdo-icon.svg
  open-graph:
    title: "Groovy Weirdo Art" #Repeated for open graph seperately due to Quarto bug
    description: "Groovy Weirdo art portfolio and shop"
    image: "assets/images/groovy-weirdo-logo-360x180.png"
    image-width: 1200
    image-height: 630
  navbar:
    title: false
    logo: large
    logo-alt: "Groovy Weirdo logo linked to home page"
    search: false
    left:
      - href: index.md   # Home page link
        text: Home
      - href: pages/about.md  # About link
        text: About
      - href: pages/portfolio.md   # Portfolio
        text: Portfolio
      - href: pages/shop.md   # Shop
        text: Shop
        
  # Define website footer
  page-footer:
    background: primary #I dont like the footer background when there isn't alot of content on the page
    border: false
    left:
      - icon: instagram
        href: https://www.instagram.com/groovyweirdo_/
        aria-label: Instagram
      - icon: tiktok
        href: https://www.tiktok.com/@groovy_weirdoo/
        aria-label: TikTok
    right: "© 2026 Groovy Weirdo. All rights reserved."

        
format:
  html:
    theme:
      - default
      - custom.scss           # Injected on top of the brand layer
    css: assets/styles.css      # Links an optional custom CSS file
    toc: false            # Adds a Table of Contents to pages
    page-layout: full
    from: markdown+emoji