project:
  type: website
  output-dir: docs  # GitHub Pages will serve from here
  resources: 
    - CNAME
  render: 
    - index.qmd
    - about.qmd
    - portfolio.qmd
    - shop.qmd
website:
  site-url: "https://www.groovyweirdo.com"
  title: "Groovy Weirdo Art"
  description: "Groovy Weirdo art portfolio and shop"
  image: "assets/images/groovy-weirdo-logo-360x180.png"
  favicon: assets/images/groovy-weirdo-icon.svg
  open-graph:
    title: "Groovy Weirdo Art"
    description: "Groovy Weirdo art portfolio and shop"
    image: "assets/images/groovy-weirdo-logo-360x180.png"
    image-width: 1200
    image-height: 630
  navbar:
    title: false
    logo: large
    search: false
    left:
      - href: index.html   # Home page link
        text: Home
      - href: about.html  # About link
        text: About
      - href: portfolio.html   # Portfolio
        text: Portfolio
    right:
      - href: shop.qmd   # Shop
        text: Shop
format:
  html:
    theme: default         # Sets the site's visual style
    css: assets/styles.css      # Links an optional custom CSS file
    # include-in-header: _includes/meta.html # trying to get a rich text preview
    toc: false            # Adds a Table of Contents to pages