project:
  type: website
  output-dir: docs  # GitHub Pages will serve from here
  resources: 
    - CNAME
  render: 
    - index.qmd
    - about.qmd
    - portfolio.qmd
    - shop.qmd
website:
  title: "Groovy Weirdo"
  favicon: assets/images/groovy-weirdo-icon.svg
  navbar:
    title: false
    logo: large
    search: false
    left:
      - href: index.html   # Home page link
        text: Home
      - href: about.html  # About link
        text: About
      - href: portfolio.html   # Portfolio
        text: Portfolio
    right:
      - href: shop.qmd   # Shop
        text: Shop
format:
  html:
    theme: default         # Sets the site's visual style
    css: assets/styles.css      # Links an optional custom CSS file
    toc: false            # Adds a Table of Contents to pages